### ISSUE TITLE
progressive difficulty

### ISSUE THREAD

**Issue by j4kim** [j4kim/dom-at-home#8]

**Comment by j4kim** [comment]
@GiantCupcake il faudrait une fonction de ce style, je ne sais pas comment faire ?
![IMG_0935](https://user-images.githubusercontent.com/19431331/119352793-6929c100-bca2-11eb-8c97-e2f28c743a94.jpg)

**Comment by j4kim** [comment]
@GiantCupcake up

**Comment by GiantCupcake** [comment]
1 - e ^ (-a x)

e: exponentielle
^: à la puissance
a: constante
1 : la limite à atteindre

**Comment by j4kim** [comment]
@GiantCupcake merci mais ça marche pas top, ou alors je ne trouve pas les bons paramètres
https://www.wolframalpha.com/input/?i=plot+%2812+-+e+%5E+%28-1+x%29%29+from+x%3D0+to+100

**Comment by j4kim** [comment]
Est-ce qu'on ferait pas mieux de partir de 1/x ?

**Comment by j4kim** [comment]
Du genre
https://www.wolframalpha.com/input/?i=plot+14++%2B+%2812+*+%28-1%2F%280.02x%2B1%29%29%29+from+x%3D0+to+200
